### ISSUE TITLE
Missing react peer dependency

### ISSUE THREAD

**Issue by MrLoh** [react-native-community/react-native-statusbar#11]
Doesn't compile for me with `Unable to resolve module `React` from `/Users/tolo/Repos/Cinuru/app/node_modules/@react-native-community/status-bar/js/StatusBar.js`: Module `React` does not exist in the Haste module map or in these directories:
  .../app/node_modules`

probably the missing React peer dependency declaration

**Comment by MrLoh** [comment]
I guess this whole package is not really usable at all yet, all the import statements in the code are also broken. Was this tested at all?

**Comment by dmtrKovalenko** [comment]
https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js

The imports is not an issue. And react Peer Dependency should not be an issue. Everything worked for me perfectly. Let me test it a bit

**Comment by dmtrKovalenko** [comment]
Published 1.0.2 with fixes. @MrLoh can you please check is it working for you now?

**Comment by MrLoh** [comment]
Great yeah working now, it might have been an special issue with my metro or babel config.
