### ISSUE TITLE
build.gradle add google()

### ISSUE THREAD

**Issue by xdcheng** [react-native-community/react-native-statusbar#15]
My English is poor. 
I do not understand native. I add `react-native-statusbar` to react-native v0.59.1. but i get this problem:

![QQ截图20190321154205](https://user-images.githubusercontent.com/27407218/54738612-f0290d80-4bef-11e9-9f0d-490125cf2b34.png)

then, I tried to add a `google()`  to `build.gradle` in android project. it run.

![QQ截图20190321154733](https://user-images.githubusercontent.com/27407218/54738815-b278b480-4bf0-11e9-904c-4f581037fc35.png)

**Comment by dmtrKovalenko** [comment]
Closed by #14
