### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-statusbar#2]
@dmtrKovalenko could you let me know your npm username so I can give you access to publish this package?

**Comment by dmtrKovalenko** [comment]
@cpojer -> dmtr.kovalenko

**Comment by cpojer** [comment]
Awesome! I added you – can you let me know once you published this package?

**Comment by dmtrKovalenko** [comment]
@cpojer Published to npm - https://www.npmjs.com/package/@react-native-community/status-bar

Also I would like to add to this repo:
1. Tests 
2. Typescript support
3. Better documentation + badges 😮

**Comment by dmtrKovalenko** [comment]
And also will create a commit to depracte status-bar module in core
