### ISSUE TITLE
StatusBarManager.DEFAULT_BACKGROUND_COLOR Bug Issue

### ISSUE THREAD

**Issue by kuraydev** [react-native-community/react-native-statusbar#29]
# Bug

After status-bar is excluded from original React Native, I got this error and could not find anywhere else to resolve the issue. Simply, installed the library from npm, link it but after the run, this error appears.

## Environment info

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 1.55 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-asset: 1.1.3
      react-native-cli: 2.0.1
      react-native: 0.59.8

```

**Library version:**  1.0.3

Describe what you expected to happen:

1. Just works as normal.

![Simulator Screen Shot - iPhone X - 2019-07-14 at 22 05 06](https://user-images.githubusercontent.com/6813862/61188437-b17bff00-a687-11e9-9450-e73a031d2b36.png)

**Comment by gabrielbull** [comment]
As is the case with most react-native libraries now a days, you need to do a pod install after installing the library. An update to the README might help here. Most likely, you will want to do the pod install on every yarn install, so having a postinstall command might help.

In your package.json:

```
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "cd ios && pod install"
  },
```

Otherwise, just browse to the `ios` directory and run the command: `pod install`

**Comment by kuraydev** [comment]
I encountered this error before RN 60+, so I believe that it will work with `autolinking` & `pod install`. I closed this issue for now. Thank you @gabrielbull :)

**Comment by dmtrKovalenko** [comment]
Make sure that this project is on hold #28
